# Generated by Django 4.2.6 on 2023-11-23 14:41

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_manager", "0007_alter_surgery_surgery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="allergy_description",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descripción de alergias",
            ),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="allergy",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("00", "Ácaros del polvo"),
                    ("01", "Alimentos"),
                    ("02", "Hongos"),
                    ("03", "Insectos picadores"),
                    ("04", "Moho"),
                    ("05", "Pasto"),
                    ("06", "Plantas"),
                    ("07", "Productos químicos"),
                    ("08", "Proteínas de saliva de pulgas"),
                    ("09", "Productos de cuidado personal"),
                    ("10", "Polen"),
                    ("11", "Polvo"),
                    ("12", "Medicamentos"),
                    ("13", "Pelaje de otros animales"),
                    ("14", "Plumas"),
                    ("15", "Productos de limpieza y detergentes"),
                    ("16", "Sustancias químicas en el entorno "),
                    ("17", "Polvo de heno"),
                    ("18", "Humo de tabaco"),
                    (
                        "19",
                        "Sustancias presentes en juguetes y accesorios para mascotas",
                    ),
                    ("20", "Virus y bacterias"),
                ],
                max_length=25,
                null=True,
                verbose_name="Alergias",
            ),
        ),
    ]
