# Generated by Django 4.2.6 on 2023-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=50)),
                ('national_helpline', models.CharField(max_length=25)),
                ('helpline_abroad', models.CharField(max_length=25)),
                ('nationality', models.CharField(choices=[('AL', 'ALBANIA'), ('ES', 'SPAIN')], default='SPAIN', max_length=2)),
                ('start_date', models.DateTimeField()),
                ('renovation_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Poliza de seguro',
                'verbose_name_plural': 'Polizas de seguros',
            },
        ),
    ]
