# Generated by Django 4.2.6 on 2024-05-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_manager', '0006_alter_insurancepolice_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolice',
            name='nationality',
        ),
    ]
