# Generated by Django 4.2.6 on 2023-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, choices=[('PROP', 'PROPIETARIO'), ('PROT', 'PROTECTORA'), ('ADMI', 'ADMINISTRADOR'), ('CLIN', 'CLINICA')], default='ADMI', max_length=4, verbose_name='Permisos'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='token_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='town',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(blank=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(blank=True, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='opt_generator_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
