# Generated by Django 4.2.6 on 2024-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0006_rename_opt_generator_code_baseuser_otp_generator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='town',
            field=models.CharField(blank=True, choices=[('18', 'Granada'), ('41', 'Sevilla'), ('11', 'Cádiz'), ('29', 'Málaga'), ('23', 'Jaén'), ('14', 'Córdoba'), ('04', 'Almería'), ('21', 'Huelva'), ('50', 'Zaragoza'), ('44', 'Teruel'), ('22', 'Huesca'), ('33', 'Asturias'), ('07', 'Illes Balears'), ('35', 'Las Palmas'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('09', 'Burgos'), ('42', 'Soria'), ('34', 'Palencia'), ('47', 'Valladolid'), ('49', 'Zamora'), ('05', 'Ávila'), ('37', 'Salamanca'), ('24', 'León'), ('19', 'Guadalajara'), ('13', 'Ciudad Real'), ('02', 'Albacete'), ('45', 'Toledo'), ('16', 'Cuenca'), ('43', 'Tarragona'), ('08', 'Barcelona'), ('25', 'Lleida'), ('17', 'Girona'), ('12', 'Castelló'), ('46', 'València'), ('03', 'Alacant'), ('10', 'Cáceres'), ('06', 'Badajoz'), ('32', 'Ourense'), ('15', 'A Coruña'), ('36', 'Pontevedra'), ('27', 'Lugo'), ('28', 'Madrid'), ('30', 'Murcia'), ('31', 'Navarra'), ('20', 'Gipuzkoa'), ('48', 'Bizkaia'), ('01', 'Araba'), ('26', 'La Rioja'), ('51', 'Ceuta'), ('52', 'Melilla')], max_length=2, null=True, verbose_name='Ciudad'),
        ),
    ]
