# Generated by Django 4.2.6 on 2023-10-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insurance_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("specie", models.CharField(max_length=25)),
                ("breed", models.CharField(max_length=25)),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "FEMIA"), ("M", "MACHO")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("birth_date", models.DateTimeField()),
                ("color", models.CharField(max_length=15)),
                ("notable_characteristics", models.CharField(max_length=255)),
                ("ppp", models.BooleanField(default=False)),
                ("atttitudes", models.CharField(max_length=15)),
                (
                    "insurance_police",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance_manager.insurancepolice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
            },
        ),
    ]
