# Generated by Django 4.2.6 on 2023-11-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_manager', '0004_remove_animal_animal_marking_remove_animal_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(verbose_name='Fecha de fallecimiento')),
                ('cause', models.CharField(max_length=50, verbose_name='Causa')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_manager.animal', verbose_name='Animal')),
                ('veterinary_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Clinica Veterinaria')),
            ],
        ),
    ]
