# Generated by Django 4.2.6 on 2023-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_manager", "0005_deathrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Imagen de perfil"
            ),
        ),
    ]
