# Generated by Django 4.2.6 on 2023-11-23 12:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet_manager", "0014_alter_deathrecord_cause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="color",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("00", "Amarillo"),
                    ("01", "Azul"),
                    ("02", "Blanco"),
                    ("03", "Gris"),
                    ("04", "Marrón"),
                    ("05", "Naranja"),
                    ("06", "Negro"),
                    ("07", "Rojo"),
                    ("08", "Verde"),
                    ("09", "Rosa"),
                ],
                max_length=50,
                verbose_name="Color",
            ),
        ),
    ]
