# Generated by Django 4.2.6 on 2023-11-23 12:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet_manager", "0015_alter_animal_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="atttitudes",
        ),
        migrations.AddField(
            model_name="animal",
            name="attitudes",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("00", "Ágil"),
                    ("01", "Alerta"),
                    ("02", "Amistoso"),
                    ("03", "Astuto"),
                    ("04", "Cariñoso"),
                    ("05", "Caución"),
                    ("06", "Dócil"),
                    ("07", "Energético"),
                    ("08", "Fiel"),
                    ("09", "Independiente"),
                    ("10", "Inteligente"),
                    ("11", "Juguetón"),
                    ("12", "Leal"),
                    ("13", "Obediente"),
                    ("14", "Protector"),
                    ("15", "Rápido"),
                    ("16", "Reservado"),
                    ("17", "Sociable"),
                    ("18", "Valiente"),
                    ("19", "Versátil"),
                ],
                max_length=15,
                null=True,
                verbose_name="Actitudes",
            ),
        ),
    ]
