# Generated by Django 4.2.6 on 2024-05-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_manager', '0019_alter_passport_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='nationality',
        ),
    ]
