#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DJANGO_DATABASE_USER;
    CREATE DATABASE $DJANGO_DATABASE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DATABASE_DB TO $DJANGO_DATABASE_USER;
    ALTER USER $DJANGO_DATABASE_USER WITH PASSWORD '$DJANGO_DATABASE_PASSWORD';
EOSQL